#!/usr/bin/env python3
"""Compile the complete patched native VM and verify emitted VOB block replay.

Pass unpacked patched libdvdnav/libdvdread source and fixtures generated by
create-dvd-title-fixtures.py. No private paths, downloads or Android are used.
MSVC must run in a developer environment; otherwise the compiler defaults to cc.
"""
import argparse
import os
from pathlib import Path
import shutil
import subprocess
import tempfile

NAV_FILES = ['dvdnav.c', 'highlight.c', 'logger.c', 'navigation.c', 'read_cache.c',
             'searching.c', 'settings.c', 'title_layout.c', 'vm/decoder.c',
             'vm/getset.c', 'vm/play.c', 'vm/vm.c', 'vm/vmcmd.c', 'vm/vmget.c']
READ_FILES = ['dvd_reader.c', 'dvd_iso9660.c', 'dvd_input.c', 'dvd_udf.c',
              'ifo_read.c', 'logger.c', 'md5.c', 'bitreader.c', 'nav_read.c']


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('source', type=Path)
    parser.add_argument('--dvdread-source', type=Path, required=True)
    parser.add_argument('--fixtures', type=Path, required=True)
    parser.add_argument('--cc', default=os.environ.get('CC', 'cc'))
    args = parser.parse_args()
    msvc = Path(args.cc).stem in ('cl', 'clang-cl')
    test = Path(__file__).with_name('dvdnav-block-replay.c').resolve()
    read = args.dvdread_source.resolve()
    with tempfile.TemporaryDirectory(prefix='dvdnav-block-replay-') as directory:
        work = Path(directory)
        nav = work/'dvdnav'
        shutil.copytree(args.source.resolve(), nav)
        # Existing host-only logging macro compatibility; VM/seek code is unchanged.
        if msvc:
            path = nav/'src/dvdnav_internal.h'
            data = path.read_text().replace('#define printerrf(str) \\\n', '#define printerrf(...) \\\n')
            path.write_text(data.replace('snprintf(this->err_str, MAX_ERR_LEN, str)',
                                         'snprintf(this->err_str, MAX_ERR_LEN, __VA_ARGS__)'))
            path = nav/'src/read_cache.c'
            path.write_text(path.read_text().replace('define dprintf(fmt, str)', 'define dprintf(fmt, ...)'))
        config = '#pragma once\n#define PACKAGE_STRING "libdvdnav 7.0.0"\n#define VERSION "7.0.0"\n#define HAVE_STATIC_ASSERT 1\n#define UNUSED\n'
        config += '#include <winsock2.h>\n' if msvc else '#define HAVE_GETTIMEOFDAY 1\n'
        (work/'config.h').write_text(config)
        for name, source, substitutions in (
            ('dvdnav', nav, {'DVDNAV_MAJOR':7, 'DVDNAV_MINOR':0, 'DVDNAV_SUB':0}),
            ('dvdread', read, {'DVDREAD_VERSION_MAJOR':7, 'DVDREAD_VERSION_MINOR':0, 'DVDREAD_VERSION_MICRO':1})):
            data = (source/f'src/{name}/version.h.in').read_text()
            for key, value in substitutions.items():
                data = data.replace('@'+key+'@',str(value))
            (work/name).mkdir(exist_ok=True)
            (work/name/'version.h').write_text(data)
        includes = [work, read, read/'src', nav/'src']
        if msvc:
            includes += [read/'msvc/include', read/'msvc/contrib/dirent']
        sources = [read/'src'/name for name in READ_FILES]+[nav/'src'/name for name in NAV_FILES]+[test]
        objects = []
        for i, source in enumerate(sources):
            obj = work/(str(i)+('.obj' if msvc else '.o'))
            objects.append(obj)
            strict = source == test or source.name == 'title_layout.c'
            if msvc:
                flags = ['/W4','/WX','/wd4100','/wd4244','/wd4996'] if strict else ['/W0']
                command = [args.cc,'/nologo','/std:c11','/Zc:preprocessor','/D_CRT_SECURE_NO_WARNINGS','/DHAVE_CONFIG_H']+flags
                command += [f'/I{path}' for path in includes]+['/c',str(source),f'/Fo:{obj}']
            else:
                flags = ['-Wall','-Wextra','-Werror','-Wno-unused-parameter','-Wno-sign-compare'] if strict else []
                command = [args.cc,'-std=c11','-D_DEFAULT_SOURCE','-D_FILE_OFFSET_BITS=64','-DHAVE_CONFIG_H']+flags
                command += [v for path in includes for v in ('-I',str(path))]+['-c',str(source),'-o',str(obj)]
            subprocess.run(command,cwd=work,check=True)
        exe = work/('test.exe' if msvc else 'test')
        command = ([args.cc,'/nologo']+[str(p) for p in objects]+[f'/Fe:{exe}']) if msvc else (
            [args.cc]+[str(p) for p in objects]+['-pthread','-ldl','-o',str(exe)])
        subprocess.run(command,cwd=work,check=True)
        subprocess.run([str(exe),str(args.fixtures.resolve())],cwd=work,check=True)


if __name__ == '__main__':
    main()
